=== netboy001/OpenMetadata/umetadata-spec/src/main/resources/json/schema/tests/testDefinition.json
{
  "$id": "https://wondersgroup.com/schema/tests/testDefinition.json",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "TestDefinition",
  "description": "Test Definition is a type of test using which test cases are created to capture data quality tests against data entities.",
  "type": "object",
  "javaType": "org.umetadata.schema.tests.TestDefinition",
  "javaInterfaces": ["org.umetadata.schema.EntityInterface"],
  "definitions": {
    "testPlatform": {
      "javaType": "org.umetadata.schema.tests.TestPlatform",
      "description": "This schema defines the platform where tests are defined and ran.",
      "type": "string",
      "enum": [
        "UMetadata",
        "GreatExpectations",
        "dbt",
        "Deequ",
        "Soda",
        "Other"
      ]
    },
    "testDataType": {
      "javaType": "org.umetadata.schema.type.TestCaseParameterDataType",
      "description": "This enum defines the type of data stored in a column.",
      "type": "string",
      "enum": [
        "NUMBER",
        "INT",
        "FLOAT",
        "DOUBLE",
        "DECIMAL",
        "TIMESTAMP",
        "TIME",
        "DATE",
        "DATETIME",
        "ARRAY",
        "MAP",
        "SET",
        "STRING",
        "BOOLEAN"
      ]
    },
    "entityType": {
      "javaType": "org.umetadata.schema.type.TestDefinitionEntityType",
      "description": "This enum defines the type for which this test definition applies to.",
      "type": "string",
      "enum": [
        "TABLE",
        "COLUMN"
      ]
    },
    "testCaseParameterDefinition": {
      "type": "object",
      "javaType": "org.umetadata.schema.tests.TestCaseParameter",
      "description": "This schema defines the parameters that can be passed for a Test Case.",
      "properties": {
        "name": {
          "description": "name of the parameter.",
          "type": "string"
        },
        "displayName": {
          "description": "Display Name that identifies this parameter name.",
          "type": "string"
        },
        "dataType": {
          "description": "Data type of the parameter (int, date etc.).",
          "$ref": "#/definitions/testDataType"
        },
        "description": {
          "description": "Description of the parameter.",
          "$ref": "../type/basic.json#/definitions/markdown"
        },
        "required": {
          "description": "Is this parameter required.",
          "type": "boolean",
          "default": false
        },
        "optionValues": {
          "description": "List of values that can be passed for this parameter.",
          "type": "array",
          "default": []
        },
        "validationRule": {
          "type": "object",
          "javaType": "org.umetadata.schema.tests.TestCaseParameterValidationRule",
          "description": "Validation for the test parameter value.",
          "properties": {
            "parameterField": {
              "description": "Name of the parameter to validate against.",
              "type": "string"
            },
            "rule": {
              "javaType": "org.umetadata.schema.type.TestCaseParameterValidationRuleType",
              "description": "This enum defines the type to use for a parameter validation rule.",
              "type": "string",
              "enum": [
                  "EQUALS",
                  "NOT_EQUALS",
                  "GREATER_THAN_OR_EQUALS",
                  "LESS_THAN_OR_EQUALS"
              ]
            }
          }
        }
      }
    },
    "dataQualityDimensions": {
      "javaType": "org.umetadata.schema.type.DataQualityDimensions",
      "description": "This enum defines the dimension a test case belongs to.",
      "type": "string",
      "enum": [
        "Completeness",
        "Accuracy",
        "Consistency",
        "Validity",
        "Uniqueness",
        "Integrity",
        "SQL",
        "NoDimension"
      ]
    }
  },
  "properties": {
    "id": {
      "description": "Unique identifier of this test case definition instance.",
      "$ref": "../type/basic.json#/definitions/uuid"
    },
    "name": {
      "description": "Name that identifies this test case.",
      "$ref": "../type/basic.json#/definitions/testCaseEntityName"
    },
    "displayName": {
      "description": "Display Name that identifies this test case.",
      "type": "string"
    },
    "fullyQualifiedName": {
      "description": "FullyQualifiedName same as `name`.",
      "$ref": "../type/basic.json#/definitions/fullyQualifiedEntityName"
    },
    "description": {
      "description": "Description of the testcase.",
      "$ref": "../type/basic.json#/definitions/markdown"
    },
    "entityType": {
      "$ref": "#/definitions/entityType"
    },
    "testPlatforms": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/testPlatform"
      }
    },
    "supportedDataTypes": {
      "type": "array",
      "items": {
        "$ref": "../entity/data/table.json#/definitions/dataType"
      }
    },
    "parameterDefinition": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/testCaseParameterDefinition"
      }
    },
    "dataQualityDimension": {
      "$ref": "#/definitions/dataQualityDimensions"
    },
    "owners": {
      "description": "Owners of this TestCase definition.",
      "$ref": "../type/entityReferenceList.json",
      "default": null
    },
    "provider" : {
      "$ref": "../type/basic.json#/definitions/providerType"
    },
    "version": {
      "description": "Metadata version of the entity.",
      "$ref": "../type/entityHistory.json#/definitions/entityVersion"
    },
    "updatedAt": {
      "description": "Last update time corresponding to the new version of the entity in Unix epoch time milliseconds.",
      "$ref": "../type/basic.json#/definitions/timestamp"
    },
    "updatedBy": {
      "description": "User who made the update.",
      "type": "string"
    },
    "href": {
      "description": "Link to the resource corresponding to this entity.",
      "$ref": "../type/basic.json#/definitions/href"
    },
    "changeDescription": {
      "description": "Change that lead to this version of the entity.",
      "$ref": "../type/entityHistory.json#/definitions/changeDescription"
    },
    "incrementalChangeDescription": {
      "description": "Change that lead to this version of the entity.",
      "$ref": "../type/entityHistory.json#/definitions/changeDescription"
    },
    "deleted": {
      "description": "When `true` indicates the entity has been soft deleted.",
      "type": "boolean",
      "default": false
    },
    "supportsRowLevelPassedFailed": {
      "description": "When `true` indicates the test case supports row level passed/failed.",
      "type": "boolean",
      "default": false
    },
    "domains" : {
      "description": "Domains the asset belongs to. When not set, the asset inherits the domain from the parent it belongs to.",
      "$ref": "../type/entityReferenceList.json"
    },
    "supportsDynamicAssertion": {
      "description": "When `true` indicates the test case supports dynamic assertions.",
      "type": "boolean",
      "default": false
    },
    "enabled": {
      "description": "When `true` indicates the test definition is available for creating test cases. System test definitions can only be disabled by users with appropriate permissions.",
      "type": "boolean",
      "default": true
     },
    "supportedServices": {
      "description": "List of services that this test definition supports. When empty, it implies all services are supported.",
      "type": "array",
      "items": {
        "type": "string"
      },
      "default": []
     },
    "sqlExpression": {
      "description": "SQL expression template for custom SQL-based test definitions. Supports substitution variables: {table} and {column} for runtime entity references, and {{paramName}} for user-defined parameters. This field is only applicable for test definitions with testPlatforms set to 'UMetadata' and is used to execute custom SQL queries for data quality validation.",
      "$ref": "../type/basic.json#/definitions/sqlQuery"
    },
    "validatorClass": {
      "description": "Class name of the validator to use for this test definition. This field is used to map the test definition to its corresponding validation logic in the data quality framework.",
      "type": "string"
    }
  },
  "required": ["name", "testPlatforms"],
  "additionalProperties": false
}

=== netboy001/OpenMetadata/umetadata-service/src/main/resources/json/data/tests/columnValuesToBeBetween.json
{
  "name": "columnValuesToBeBetween",
  "fullyQualifiedName": "columnValuesToBeBetween",
  "displayName": "Column Values To Be Between",
  "description": "This schema defines the test ColumnValuesToBeBetween. Test the values in a column to be between minimum and maximum value. ",
  "entityType": "COLUMN",
  "testPlatforms": ["UMetadata"],
  "supportedDataTypes": ["NUMBER", "INT", "FLOAT", "DOUBLE", "DECIMAL", "TINYINT", "SMALLINT", "BIGINT", "BYTEINT", "TIMESTAMP", "TIMESTAMPZ","DATETIME", "DATE"],
  "parameterDefinition": [
    {
      "name": "minValue",
      "displayName": "Min",
      "description": "The {minValue} value for the column entry. If minValue is not included, maxValue is treated as upperBound and there will be no minimum",
      "dataType": "INT",
      "validationRule": {
        "parameterField": "maxValue",
        "rule": "LESS_THAN_OR_EQUALS"
      }
    },
    {
      "name": "maxValue",
      "displayName": "Max",
      "description": "The {maxValue} value for the column entry. if maxValue is not included, minValue is treated as lowerBound and there will be no maximum",
      "dataType": "INT",
      "validationRule": {
          "parameterField": "minValue",
          "rule": "GREATER_THAN_OR_EQUALS"
      }
    }
  ],
  "supportsRowLevelPassedFailed": true,
  "supportsDynamicAssertion": true,
  "provider": "system",
  "enabled": true,
  "dataQualityDimension": "Accuracy",
  "validatorClass": "ColumnValuesToBeBetweenValidator"
}

=== netboy001/OpenMetadata/umetadata-service/src/main/resources/json/data/tests/columnValueToBeAtExpectedLocation.json
{
    "name": "columnValuesToBeAtExpectedLocation",
    "fullyQualifiedName": "columnValuesToBeAtExpectedLocation",
    "displayName": "Column Values To Be At Expected Location",
    "description": "This schema defines the test ColumnValuesToBeAtExpectedLocation. Test the lat/long values in a column to be at the specified location in the reference column.",
    "entityType": "COLUMN",
    "testPlatforms": ["UMetadata"],
    "supportedDataTypes": ["BYTES", "STRING", "MEDIUMTEXT", "TEXT", "CHAR", "VARCHAR","NUMBER", "INT", "FLOAT", "DOUBLE", "DECIMAL", "TINYINT", "SMALLINT", "BIGINT", "BYTEINT"],
    "parameterDefinition": [
      {
        "name": "locationReferenceType",
        "displayName": "Location Reference Type",
        "description": "The type of the location reference column.",
        "dataType": "ARRAY",
        "optionValues": ["CITY", "POSTAL_CODE"],
        "required": true
      },
      {
        "name": "longitudeColumnName",
        "displayName": "Longitude Column Name (X)",
        "description": "The longitude column name in the table.",
        "dataType": "STRING",
        "required": true
      },
      {
        "name": "latitudeColumnName",
        "displayName": "Latitude Column Name (Y)",
        "description": "The latitude column name in the table.",
        "dataType": "STRING",
        "required": true
      },
      {
        "name": "radius",
        "displayName": "Radius (in meters) from the expected location",
        "description": "The radius in meters from the expected location. The test will check if the lat/long values are within the location + the radius.",
        "dataType": "FLOAT",
        "required": true
      }
    ],
    "supportsRowLevelPassedFailed": false,
    "provider": "system",
  "enabled": true,
    "dataQualityDimension": "Accuracy",
    "validatorClass": "ColumnValuesToBeAtExpectedLocationValidator"
  }

=== netboy001/OpenMetadata/umetadata-service/src/main/resources/json/data/tests/tableRowInsertedCountToBeBetween.json
{
    "name": "tableRowInsertedCountToBeBetween",
    "fullyQualifiedName": "tableRowInsertedCountToBeBetween",
    "displayName": "Table Row Inserted Count To be Between",
    "description": "This schema defines the test tableRowInsertedCountToBeBetween. Test the number of rows inserted is between x and y.",
    "entityType": "TABLE",
    "testPlatforms": ["UMetadata"],
    "parameterDefinition": [
      {
        "name": "min",
        "displayName": "Min Row Count",
        "description": "Lower Bound of the Count",
        "dataType": "INT",
        "required": false,
        "validationRule": {
          "parameterField": "max",
          "rule": "LESS_THAN_OR_EQUALS"
        }
      },
      {
        "name": "max",
        "displayName": "Max Row Count",
        "description": "Upper Bound of the Count",
        "dataType": "INT",
        "required": false,
        "validationRule": {
          "parameterField": "min",
          "rule": "GREATER_THAN_OR_EQUALS"
        }
      },
      {
        "name": "columnName",
        "displayName": "Column Name",
        "description": "Name of the Column. It should be a timestamp, date or datetime field.",
        "dataType": "STRING",
        "required": true
      },
      {
        "name": "rangeType",
        "displayName": "Range Type",
        "description": "One of 'HOUR', 'DAY', 'MONTH', 'YEAR'",
        "dataType": "STRING",
        "required": true
      },
      {
        "name": "rangeInterval",
        "displayName": "Interval",
        "description": "Interval Range. E.g. if rangeInterval=1 and rangeType=DAY, we'll check the numbers of rows inserted where columnName=-1 DAY",
        "dataType": "INT",
        "required": true
      }
    ],
    "provider": "system",
  "enabled": true,
    "dataQualityDimension": "Integrity",
    "validatorClass": "TableRowInsertedCountToBeBetweenValidator"
  }

=== netboy001/OpenMetadata/umetadata-service/src/main/resources/json/data/tests/columnValuesMissingCountToBeEqual.json
{
  "name": "columnValuesMissingCount",
  "fullyQualifiedName": "columnValuesMissingCount",
  "displayName": "Column Values Missing Count",
  "description": "This schema defines the test ColumnValuesMissingCount. Test the column values missing count to be equal to given number. ",
  "entityType": "COLUMN",
  "testPlatforms": ["UMetadata"],
  "supportedDataTypes": ["NUMBER","TINYINT","SMALLINT","INT","BIGINT","BYTEINT","BYTES","FLOAT","DOUBLE","DECIMAL","NUMERIC","TIMESTAMP","TIMESTAMPZ","TIME","DATE","DATETIME","INTERVAL","STRING","MEDIUMTEXT","TEXT","CHAR","VARCHAR","BOOLEAN","BINARY","VARBINARY","ARRAY","BLOB","LONGBLOB","MEDIUMBLOB","MAP","STRUCT","UNION","SET","GEOGRAPHY","ENUM","JSON","UUID","VARIANT","GEOMETRY","POINT","POLYGON","LOWCARDINALITY"],
  "parameterDefinition": [
    {
      "name": "missingCountValue",
      "displayName": "Missing Count",
      "description": "No.of missing values to be equal to.",
      "dataType": "INT",
      "required": true
    },
    {
      "name": "missingValueMatch",
      "displayName": "Missing Value to Match",
      "description": "By default match all null and empty values to be missing. This field allows us to configure additional strings such as N/A, NULL as missing strings as well.",
      "dataType": "STRING"
    }
  ],
  "provider": "system",
  "enabled": true,
  "dataQualityDimension": "Completeness",
  "validatorClass": "ColumnValuesMissingCountValidator"
}

=== netboy001/OpenMetadata/umetadata-service/src/main/resources/json/data/tests/tableColumnCountToBeBetween.json
{
  "name": "tableColumnCountToBeBetween",
  "fullyQualifiedName": "tableColumnCountToBeBetween",
  "displayName": "Table Column Count To Be Between",
  "description": "This schema defines the test TableColumnCountToBeBetween. Test the number of columns to be between min max value.",
  "entityType": "TABLE",
  "testPlatforms": ["UMetadata"],
  "parameterDefinition": [
    {
      "name": "minColValue",
      "displayName": "Min",
      "description": "Expected number of columns should be greater than or equal to {minValue}. If minValue is not included, maxValue is treated as upperBound and there will be no minimum number of column",
      "dataType": "INT",
      "validationRule": {
        "parameterField": "maxColValue",
        "rule": "LESS_THAN_OR_EQUALS"
      }
    },
    {
      "name": "maxColValue",
      "displayName": "Max",
      "description": "Expected number of columns should be less than or equal to {maxValue}. If maxValue is not included, minValue is treated as lowerBound and there will be no maximum number of column",
      "dataType": "INT",
      "validationRule": {
          "parameterField": "minColValue",
          "rule": "GREATER_THAN_OR_EQUALS"
      }
    }
  ],
  "provider": "system",
  "enabled": true,
  "dataQualityDimension": "Integrity",
  "validatorClass": "TableColumnCountToBeBetweenValidator"
}

=== netboy001/OpenMetadata/umetadata-service/src/main/resources/json/data/tests/columnValueStdDevToBeBetween.json
{
    "name": "columnValueStdDevToBeBetween",
    "fullyQualifiedName": "columnValueStdDevToBeBetween",
    "displayName": "Column Value Std Dev To Be Between",
    "description": "This schema defines the test ColumnValueStdDevToBeBetween. Test the std. dev. value in a col is within a range.",
    "entityType": "COLUMN",
    "testPlatforms": ["UMetadata"],
    "supportedDataTypes": ["NUMBER", "INT", "FLOAT", "DOUBLE", "DECIMAL", "TINYINT", "SMALLINT", "BIGINT", "BYTEINT"],
    "parameterDefinition": [
      {
        "name": "minValueForStdDevInCol",
        "displayName": "Min",
        "description": "Expected std. dev value for the column to be greater or equal than",
        "dataType": "INT",
        "validationRule": {
          "parameterField": "maxValueForStdDevInCol",
          "rule": "LESS_THAN_OR_EQUALS"
        }
      },
      {
        "name": "maxValueForStdDevInCol",
        "displayName": "Max",
        "description": "Expected std. dev value for the column to be lower or equal than",
        "dataType": "INT",
        "validationRule": {
          "parameterField": "minValueForStdDevInCol",
          "rule": "GREATER_THAN_OR_EQUALS"
        }
      }
    ],
    "supportsDynamicAssertion": true,
    "provider": "system",
  "enabled": true,
    "dataQualityDimension": "Accuracy",
    "validatorClass": "ColumnValueStdDevToBeBetweenValidator"
  }

=== netboy001/OpenMetadata/umetadata-service/src/main/resources/json/data/tests/tableDiff.json
{
  "name": "tableDiff",
  "fullyQualifiedName": "tableDiff",
  "displayName": "Compare 2 tables for differences",
  "description": "Test if 2 tables have less that <threshold> diff rows.",
  "entityType": "TABLE",
  "testPlatforms": [
    "UMetadata"
  ],
  "parameterDefinition": [
    {
      "name": "keyColumns",
      "displayName": "Table 1's key columns",
      "description": "The columns to use as the key for the comparison. If not provided, it will be resolved from the primary key or unique columns. The tuples created from the key columns must be unique.",
      "dataType": "ARRAY",
      "required": false
    },
    {
      "name": "table2",
      "displayName": "Table 2",
      "description": "Fully qualified name of the table to compare against.",
      "dataType": "STRING",
      "required": true
    },
    {
      "name": "table2.keyColumns",
      "displayName": "Table 2's key columns",
      "description": "The columns in table 2 to use as comparison. If not provided, it will default to `Key Columns`, risking errors if the key columns' names have changed.",
      "dataType": "ARRAY",
      "required": false
    },
    {
      "name": "threshold",
      "displayName": "Threshold",
      "description": "Threshold to use to determine if the test passes or fails (defaults to 0).",
      "dataType": "NUMBER",
      "required": false
    },
    {
      "name": "useColumns",
      "displayName": "Use Columns",
      "description": "Limits the scope of the test to this list of columns. If not provided, all columns will be used except the key columns.",
      "dataType": "ARRAY",
      "required": false
    },
    {
      "name": "where",
      "displayName": "SQL Where Clause",
      "description": "Use this where clause to filter the rows to compare.",
      "dataType": "STRING",
      "required": false
    },
    {
      "name": "caseSensitiveColumns",
      "displayName": "Case sensitive columns",
      "description": "Use case sensitivity when comparing the columns.",
      "dataType": "BOOLEAN",
      "required": false
    }
  ],
  "provider": "system",
  "enabled": true,
  "dataQualityDimension": "Consistency",
  "supportedServices": [
    "Snowflake",
    "BigQuery",
    "Athena",
    "Redshift",
    "Postgres",
    "MySQL",
    "Mssql",
    "Oracle",
    "Trino",
    "SapHana"
  ],
  "validatorClass": "TableDiffValidator"
}
