=== netboy001/OpenMetadata/umetadata-spec/src/main/resources/json/schema/tests/testDefinition.json
{
  "$id": "https://wondersgroup.com/schema/tests/testDefinition.json",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "TestDefinition",
  "description": "Test Definition is a type of test using which test cases are created to capture data quality tests against data entities.",
  "type": "object",
  "javaType": "org.umetadata.schema.tests.TestDefinition",
  "javaInterfaces": ["org.umetadata.schema.EntityInterface"],
  "definitions": {
    "testPlatform": {
      "javaType": "org.umetadata.schema.tests.TestPlatform",
      "description": "This schema defines the platform where tests are defined and ran.",
      "type": "string",
      "enum": [
        "UMetadata",
        "GreatExpectations",
        "dbt",
        "Deequ",
        "Soda",
        "Other"
      ]
    },
    "testDataType": {
      "javaType": "org.umetadata.schema.type.TestCaseParameterDataType",
      "description": "This enum defines the type of data stored in a column.",
      "type": "string",
      "enum": [
        "NUMBER",
        "INT",
        "FLOAT",
        "DOUBLE",
        "DECIMAL",
        "TIMESTAMP",
        "TIME",
        "DATE",
        "DATETIME",
        "ARRAY",
        "MAP",
        "SET",
        "STRING",
        "BOOLEAN"
      ]
    },
    "entityType": {
      "javaType": "org.umetadata.schema.type.TestDefinitionEntityType",
      "description": "This enum defines the type for which this test definition applies to.",
      "type": "string",
      "enum": [
        "TABLE",
        "COLUMN"
      ]
    },
    "testCaseParameterDefinition": {
      "type": "object",
      "javaType": "org.umetadata.schema.tests.TestCaseParameter",
      "description": "This schema defines the parameters that can be passed for a Test Case.",
      "properties": {
        "name": {
          "description": "name of the parameter.",
          "type": "string"
        },
        "displayName": {
          "description": "Display Name that identifies this parameter name.",
          "type": "string"
        },
        "dataType": {
          "description": "Data type of the parameter (int, date etc.).",
          "$ref": "#/definitions/testDataType"
        },
        "description": {
          "description": "Description of the parameter.",
          "$ref": "../type/basic.json#/definitions/markdown"
        },
        "required": {
          "description": "Is this parameter required.",
          "type": "boolean",
          "default": false
        },
        "optionValues": {
          "description": "List of values that can be passed for this parameter.",
          "type": "array",
          "default": []
        },
        "validationRule": {
          "type": "object",
          "javaType": "org.umetadata.schema.tests.TestCaseParameterValidationRule",
          "description": "Validation for the test parameter value.",
          "properties": {
            "parameterField": {
              "description": "Name of the parameter to validate against.",
              "type": "string"
            },
            "rule": {
              "javaType": "org.umetadata.schema.type.TestCaseParameterValidationRuleType",
              "description": "This enum defines the type to use for a parameter validation rule.",
              "type": "string",
              "enum": [
                  "EQUALS",
                  "NOT_EQUALS",
                  "GREATER_THAN_OR_EQUALS",
                  "LESS_THAN_OR_EQUALS"
              ]
            }
          }
        }
      }
    },
    "dataQualityDimensions": {
      "javaType": "org.umetadata.schema.type.DataQualityDimensions",
      "description": "This enum defines the dimension a test case belongs to.",
      "type": "string",
      "enum": [
        "Completeness",
        "Accuracy",
        "Consistency",
        "Validity",
        "Uniqueness",
        "Integrity",
        "SQL",
        "NoDimension"
      ]
    }
  },
  "properties": {
    "id": {
      "description": "Unique identifier of this test case definition instance.",
      "$ref": "../type/basic.json#/definitions/uuid"
    },
    "name": {
      "description": "Name that identifies this test case.",
      "$ref": "../type/basic.json#/definitions/testCaseEntityName"
    },
    "displayName": {
      "description": "Display Name that identifies this test case.",
      "type": "string"
    },
    "fullyQualifiedName": {
      "description": "FullyQualifiedName same as `name`.",
      "$ref": "../type/basic.json#/definitions/fullyQualifiedEntityName"
    },
    "description": {
      "description": "Description of the testcase.",
      "$ref": "../type/basic.json#/definitions/markdown"
    },
    "entityType": {
      "$ref": "#/definitions/entityType"
    },
    "testPlatforms": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/testPlatform"
      }
    },
    "supportedDataTypes": {
      "type": "array",
      "items": {
        "$ref": "../entity/data/table.json#/definitions/dataType"
      }
    },
    "parameterDefinition": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/testCaseParameterDefinition"
      }
    },
    "dataQualityDimension": {
      "$ref": "#/definitions/dataQualityDimensions"
    },
    "owners": {
      "description": "Owners of this TestCase definition.",
      "$ref": "../type/entityReferenceList.json",
      "default": null
    },
    "provider" : {
      "$ref": "../type/basic.json#/definitions/providerType"
    },
    "version": {
      "description": "Metadata version of the entity.",
      "$ref": "../type/entityHistory.json#/definitions/entityVersion"
    },
    "updatedAt": {
      "description": "Last update time corresponding to the new version of the entity in Unix epoch time milliseconds.",
      "$ref": "../type/basic.json#/definitions/timestamp"
    },
    "updatedBy": {
      "description": "User who made the update.",
      "type": "string"
    },
    "href": {
      "description": "Link to the resource corresponding to this entity.",
      "$ref": "../type/basic.json#/definitions/href"
    },
    "changeDescription": {
      "description": "Change that lead to this version of the entity.",
      "$ref": "../type/entityHistory.json#/definitions/changeDescription"
    },
    "incrementalChangeDescription": {
      "description": "Change that lead to this version of the entity.",
      "$ref": "../type/entityHistory.json#/definitions/changeDescription"
    },
    "deleted": {
      "description": "When `true` indicates the entity has been soft deleted.",
      "type": "boolean",
      "default": false
    },
    "supportsRowLevelPassedFailed": {
      "description": "When `true` indicates the test case supports row level passed/failed.",
      "type": "boolean",
      "default": false
    },
    "domains" : {
      "description": "Domains the asset belongs to. When not set, the asset inherits the domain from the parent it belongs to.",
      "$ref": "../type/entityReferenceList.json"
    },
    "supportsDynamicAssertion": {
      "description": "When `true` indicates the test case supports dynamic assertions.",
      "type": "boolean",
      "default": false
    },
    "enabled": {
      "description": "When `true` indicates the test definition is available for creating test cases. System test definitions can only be disabled by users with appropriate permissions.",
      "type": "boolean",
      "default": true
     },
    "supportedServices": {
      "description": "List of services that this test definition supports. When empty, it implies all services are supported.",
      "type": "array",
      "items": {
        "type": "string"
      },
      "default": []
     },
    "sqlExpression": {
      "description": "SQL expression template for custom SQL-based test definitions. Supports substitution variables: {table} and {column} for runtime entity references, and {{paramName}} for user-defined parameters. This field is only applicable for test definitions with testPlatforms set to 'UMetadata' and is used to execute custom SQL queries for data quality validation.",
      "$ref": "../type/basic.json#/definitions/sqlQuery"
    },
    "validatorClass": {
      "description": "Class name of the validator to use for this test definition. This field is used to map the test definition to its corresponding validation logic in the data quality framework.",
      "type": "string"
    }
  },
  "required": ["name", "testPlatforms"],
  "additionalProperties": false
}

=== netboy001/OpenMetadata/umetadata-service/src/main/resources/json/data/tests/columnValuesLengthsToBeBetween.json
{
  "name": "columnValueLengthsToBeBetween",
  "fullyQualifiedName": "columnValueLengthsToBeBetween",
  "displayName": "Column Value Lengths To Be Between",
  "description": "This schema defines the test ColumnValueLengthsToBeBetween. Test the value lengths in a column to be between minimum and maximum value. ",
  "entityType": "COLUMN",
  "testPlatforms": ["UMetadata"],
  "supportedDataTypes": ["BYTES", "STRING", "MEDIUMTEXT", "TEXT", "CHAR", "VARCHAR", "ARRAY", "LOWCARDINALITY"],
  "parameterDefinition": [
    {
      "name": "minLength",
      "displayName": "Min",
      "description": "The {minLength} for the column value. If minLength is not included, maxLength is treated as upperBound and there will be no minimum value length",
      "dataType": "INT",
      "validationRule": {
        "parameterField": "maxLength",
        "rule": "LESS_THAN_OR_EQUALS"
      }
    },
    {
      "name": "maxLength",
      "displayName": "Max",
      "description": "The {maxLength} for the column value. if maxLength is not included, minLength is treated as lowerBound and there will be no maximum value length",
      "dataType": "INT",
      "validationRule": {
        "parameterField": "minLength",
        "rule": "GREATER_THAN_OR_EQUALS"
      }
    }
  ],
  "supportsRowLevelPassedFailed": true,
  "supportsDynamicAssertion": true,
  "provider": "system",
  "enabled": true,
  "dataQualityDimension": "Accuracy",
  "validatorClass": "ColumnValueLengthsToBeBetweenValidator"
}

=== netboy001/OpenMetadata/umetadata-service/src/main/resources/json/data/tests/columnValuesToBeInSet.json
{
  "name": "columnValuesToBeInSet",
  "fullyQualifiedName": "columnValuesToBeInSet",
  "displayName": "Column Values To Be In Set",
  "description": "This schema defines the test ColumnValuesToBeInSet. Test the column values are in the set.",
  "entityType": "COLUMN",
  "testPlatforms": ["UMetadata"],
  "supportedDataTypes": ["NUMBER", "INT", "FLOAT", "DOUBLE", "DECIMAL", "TINYINT", "SMALLINT", "BIGINT", "BYTEINT", "BYTES", "STRING", "MEDIUMTEXT", "TEXT", "CHAR", "VARCHAR", "BOOLEAN", "LOWCARDINALITY"],
  "parameterDefinition": [
    {
      "name": "allowedValues",
      "displayName": "Allowed Values",
      "description": "An Array of values.",
      "dataType": "ARRAY",
      "required": true
    },
    {
      "name": "matchEnum",
      "displayName": "Match enum",
      "description": "If enabled, validate that each value independently matches the enum.",
      "dataType": "BOOLEAN",
      "required": false
    }
  ],
  "supportsRowLevelPassedFailed": true,
  "provider": "system",
  "enabled": true,
  "dataQualityDimension": "Validity",
  "validatorClass": "ColumnValuesToBeInSetValidator"
}

=== netboy001/OpenMetadata/umetadata-service/src/main/resources/json/data/tests/columnValueMeanToBeBetween.json
{
    "name": "columnValueMeanToBeBetween",
    "fullyQualifiedName": "columnValueMeanToBeBetween",
    "displayName": "Column Value Mean To Be Between",
    "description": "This schema defines the test ColumnValueMeanToBeBetween. Test the mean value in a col is within a range.",
    "entityType": "COLUMN",
    "testPlatforms": ["UMetadata"],
    "supportedDataTypes": ["NUMBER", "INT", "FLOAT", "DOUBLE", "DECIMAL", "TINYINT", "SMALLINT", "BIGINT", "BYTEINT", "ARRAY", "SET"],
    "parameterDefinition": [
    {
      "name": "minValueForMeanInCol",
      "displayName": "Min",
      "description": "Expected mean value for the column to be greater or equal than",
      "dataType": "INT",
      "validationRule": {
        "parameterField": "maxValueForMeanInCol",
        "rule": "LESS_THAN_OR_EQUALS"
      }
    },
    {
      "name": "maxValueForMeanInCol",
      "displayName": "Max",
      "description": "Expected mean value for the column to be lower or equal than",
      "dataType": "INT",
      "validationRule": {
            "parameterField": "minValueForMeanInCol",
            "rule": "GREATER_THAN_OR_EQUALS"
      }
    }
  ],
  "supportsDynamicAssertion": true,
  "provider": "system",
  "enabled": true,
  "dataQualityDimension": "Accuracy",
  "validatorClass": "ColumnValueMeanToBeBetweenValidator"
}

=== netboy001/OpenMetadata/umetadata-service/src/main/resources/json/data/tests/columnValueMedianToBeBetween.json
{
    "name": "columnValueMedianToBeBetween",
    "fullyQualifiedName": "columnValueMedianToBeBetween",
    "displayName": "Column Value Median To Be Between",
    "description": "This schema defines the test ColumnValueMedianToBeBetween. Test the median value in a col is within a range.",
    "entityType": "COLUMN",
    "testPlatforms": ["UMetadata"],
    "supportedDataTypes": ["NUMBER", "INT", "FLOAT", "DOUBLE", "DECIMAL", "TINYINT", "SMALLINT", "BIGINT", "BYTEINT"],
    "parameterDefinition": [
      {
        "name": "minValueForMedianInCol",
        "displayName": "Min",
        "description": "Expected median value for the column to be greater or equal than",
        "dataType": "INT",
        "validationRule": {
          "parameterField": "maxValueForMedianInCol",
          "rule": "LESS_THAN_OR_EQUALS"
        }
      },
      {
        "name": "maxValueForMedianInCol",
        "displayName": "Max",
        "description": "Expected median value for the column to be lower or equal than",
        "dataType": "INT",
        "validationRule": {
          "parameterField": "minValueForMedianInCol",
          "rule": "GREATER_THAN_OR_EQUALS"
        }
      }
  ],
  "supportsDynamicAssertion": true,
  "provider": "system",
  "enabled": true,
  "dataQualityDimension": "Accuracy",
  "validatorClass": "ColumnValueMedianToBeBetweenValidator"
}

=== netboy001/OpenMetadata/umetadata-service/src/main/resources/json/data/tests/columnValueMaxToBeBetween.json
{
    "name": "columnValueMaxToBeBetween",
    "fullyQualifiedName": "columnValueMaxToBeBetween",
    "displayName": "Column Value Max. To Be Between",
    "description": "This schema defines the test ColumnValueMaxToBeBetween. Test the maximum value in a col is within a range.",
    "entityType": "COLUMN",
    "testPlatforms": ["UMetadata", "dbt"],
    "supportedDataTypes": ["NUMBER", "INT", "FLOAT", "DOUBLE", "DECIMAL", "TINYINT", "SMALLINT", "BIGINT", "BYTEINT"],
    "parameterDefinition": [
    {
      "name": "minValueForMaxInCol",
      "displayName": "Min",
      "description": "Expected minimum value in the column to be greater or equal than",
      "dataType": "INT",
      "validationRule": {
        "parameterField": "maxValueForMaxInCol",
        "rule": "LESS_THAN_OR_EQUALS"
      }
    },
    {
      "name": "maxValueForMaxInCol",
      "displayName": "Max",
      "description": "Expected maximum value in the column to be lower or equal than",
      "dataType": "INT",
      "validationRule": {
        "parameterField": "minValueForMaxInCol",
        "rule": "GREATER_THAN_OR_EQUALS"
      }
    }
  ],
  "supportsDynamicAssertion": true,
  "provider": "system",
  "enabled": true,
  "dataQualityDimension": "Accuracy",
  "validatorClass": "ColumnValueMaxToBeBetweenValidator"
}

=== netboy001/OpenMetadata/umetadata-service/src/main/resources/json/data/tests/columnValuesToMatchRegex.json
{
  "name": "columnValuesToMatchRegex",
  "fullyQualifiedName": "columnValuesToMatchRegex",
  "displayName": "Column Values To Match Regex Pattern",
  "description": "This schema defines the test ColumnValuesToMatchRegex. Test the values in a column to match a given regular expression. ",
  "entityType": "COLUMN",
  "testPlatforms": ["UMetadata"],
  "supportedDataTypes": ["BYTES", "STRING", "MEDIUMTEXT", "TEXT", "CHAR", "VARCHAR", "LOWCARDINALITY"],
  "parameterDefinition": [
    {
      "name": "regex",
      "displayName": "RegEx Pattern",
      "description": "The regular expression the column entries should match. For database without regex support (i.e. MSSQL, AzureSQL) this test will use `LIKE`.",
      "dataType": "STRING",
      "required": true
    }
  ],
  "supportsRowLevelPassedFailed": true,
  "provider": "system",
  "enabled": true,
  "dataQualityDimension": "Validity",
  "validatorClass": "ColumnValuesToMatchRegexValidator"
}

=== netboy001/OpenMetadata/umetadata-service/src/main/resources/json/data/tests/columnValuesToBeUnique.json
{
    "name": "columnValuesToBeUnique",
    "fullyQualifiedName": "columnValuesToBeUnique",
    "displayName": "Column Values To Be Unique",
    "description": "This schema defines the test ColumnValuesToBeUnique. Test the values in a column to be unique. ",
    "entityType": "COLUMN",
    "testPlatforms": [
        "UMetadata"
    ],
    "supportedDataTypes": [
        "NUMBER",
        "TINYINT",
        "SMALLINT",
        "INT",
        "BIGINT",
        "BYTEINT",
        "BYTES",
        "FLOAT",
        "DOUBLE",
        "DECIMAL",
        "NUMERIC",
        "TIMESTAMP",
        "TIMESTAMPZ",
        "TIME",
        "DATE",
        "DATETIME",
        "INTERVAL",
        "STRING",
        "MEDIUMTEXT",
        "TEXT",
        "CHAR",
        "VARCHAR",
        "BOOLEAN",
        "BINARY",
        "VARBINARY",
        "BLOB",
        "LONGBLOB",
        "MEDIUMBLOB",
        "MAP",
        "STRUCT",
        "UNION",
        "SET",
        "GEOGRAPHY",
        "ENUM",
        "UUID",
        "VARIANT",
        "GEOMETRY",
        "POINT",
        "POLYGON",
        "LOWCARDINALITY"
    ],
    "supportsRowLevelPassedFailed": true,
    "provider": "system",
  "enabled": true,
    "dataQualityDimension": "Uniqueness",
    "validatorClass": "ColumnValuesToBeUniqueValidator"
}

=== netboy001/OpenMetadata/umetadata-service/src/main/resources/json/data/tests/tableColumnNameToExist.json
{
    "name": "tableColumnNameToExist",
    "fullyQualifiedName": "tableColumnNameToExist",
    "displayName": "Table Column Name To Exist",
    "description": "This test defines the test TableColumnNameToExist. Test the table columns exists in the table.",
    "entityType": "TABLE",
    "testPlatforms": ["UMetadata"],
    "parameterDefinition": [
      {
        "name": "columnName",
        "displayName": "Column Name",
        "description": "Expected column of the table to exist",
        "dataType": "STRING",
        "required": true
      }
    ],
    "provider": "system",
  "enabled": true,
    "dataQualityDimension": "Integrity",
    "validatorClass": "TableColumnNameToExistValidator"
  }
