=== netboy001/OpenMetadata/umetadata-spec/src/main/resources/json/schema/tests/testDefinition.json
{
  "$id": "https://wondersgroup.com/schema/tests/testDefinition.json",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "TestDefinition",
  "description": "Test Definition is a type of test using which test cases are created to capture data quality tests against data entities.",
  "type": "object",
  "javaType": "org.umetadata.schema.tests.TestDefinition",
  "javaInterfaces": ["org.umetadata.schema.EntityInterface"],
  "definitions": {
    "testPlatform": {
      "javaType": "org.umetadata.schema.tests.TestPlatform",
      "description": "This schema defines the platform where tests are defined and ran.",
      "type": "string",
      "enum": [
        "UMetadata",
        "GreatExpectations",
        "dbt",
        "Deequ",
        "Soda",
        "Other"
      ]
    },
    "testDataType": {
      "javaType": "org.umetadata.schema.type.TestCaseParameterDataType",
      "description": "This enum defines the type of data stored in a column.",
      "type": "string",
      "enum": [
        "NUMBER",
        "INT",
        "FLOAT",
        "DOUBLE",
        "DECIMAL",
        "TIMESTAMP",
        "TIME",
        "DATE",
        "DATETIME",
        "ARRAY",
        "MAP",
        "SET",
        "STRING",
        "BOOLEAN"
      ]
    },
    "entityType": {
      "javaType": "org.umetadata.schema.type.TestDefinitionEntityType",
      "description": "This enum defines the type for which this test definition applies to.",
      "type": "string",
      "enum": [
        "TABLE",
        "COLUMN"
      ]
    },
    "testCaseParameterDefinition": {
      "type": "object",
      "javaType": "org.umetadata.schema.tests.TestCaseParameter",
      "description": "This schema defines the parameters that can be passed for a Test Case.",
      "properties": {
        "name": {
          "description": "name of the parameter.",
          "type": "string"
        },
        "displayName": {
          "description": "Display Name that identifies this parameter name.",
          "type": "string"
        },
        "dataType": {
          "description": "Data type of the parameter (int, date etc.).",
          "$ref": "#/definitions/testDataType"
        },
        "description": {
          "description": "Description of the parameter.",
          "$ref": "../type/basic.json#/definitions/markdown"
        },
        "required": {
          "description": "Is this parameter required.",
          "type": "boolean",
          "default": false
        },
        "optionValues": {
          "description": "List of values that can be passed for this parameter.",
          "type": "array",
          "default": []
        },
        "validationRule": {
          "type": "object",
          "javaType": "org.umetadata.schema.tests.TestCaseParameterValidationRule",
          "description": "Validation for the test parameter value.",
          "properties": {
            "parameterField": {
              "description": "Name of the parameter to validate against.",
              "type": "string"
            },
            "rule": {
              "javaType": "org.umetadata.schema.type.TestCaseParameterValidationRuleType",
              "description": "This enum defines the type to use for a parameter validation rule.",
              "type": "string",
              "enum": [
                  "EQUALS",
                  "NOT_EQUALS",
                  "GREATER_THAN_OR_EQUALS",
                  "LESS_THAN_OR_EQUALS"
              ]
            }
          }
        }
      }
    },
    "dataQualityDimensions": {
      "javaType": "org.umetadata.schema.type.DataQualityDimensions",
      "description": "This enum defines the dimension a test case belongs to.",
      "type": "string",
      "enum": [
        "Completeness",
        "Accuracy",
        "Consistency",
        "Validity",
        "Uniqueness",
        "Integrity",
        "SQL",
        "NoDimension"
      ]
    }
  },
  "properties": {
    "id": {
      "description": "Unique identifier of this test case definition instance.",
      "$ref": "../type/basic.json#/definitions/uuid"
    },
    "name": {
      "description": "Name that identifies this test case.",
      "$ref": "../type/basic.json#/definitions/testCaseEntityName"
    },
    "displayName": {
      "description": "Display Name that identifies this test case.",
      "type": "string"
    },
    "fullyQualifiedName": {
      "description": "FullyQualifiedName same as `name`.",
      "$ref": "../type/basic.json#/definitions/fullyQualifiedEntityName"
    },
    "description": {
      "description": "Description of the testcase.",
      "$ref": "../type/basic.json#/definitions/markdown"
    },
    "entityType": {
      "$ref": "#/definitions/entityType"
    },
    "testPlatforms": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/testPlatform"
      }
    },
    "supportedDataTypes": {
      "type": "array",
      "items": {
        "$ref": "../entity/data/table.json#/definitions/dataType"
      }
    },
    "parameterDefinition": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/testCaseParameterDefinition"
      }
    },
    "dataQualityDimension": {
      "$ref": "#/definitions/dataQualityDimensions"
    },
    "owners": {
      "description": "Owners of this TestCase definition.",
      "$ref": "../type/entityReferenceList.json",
      "default": null
    },
    "provider" : {
      "$ref": "../type/basic.json#/definitions/providerType"
    },
    "version": {
      "description": "Metadata version of the entity.",
      "$ref": "../type/entityHistory.json#/definitions/entityVersion"
    },
    "updatedAt": {
      "description": "Last update time corresponding to the new version of the entity in Unix epoch time milliseconds.",
      "$ref": "../type/basic.json#/definitions/timestamp"
    },
    "updatedBy": {
      "description": "User who made the update.",
      "type": "string"
    },
    "href": {
      "description": "Link to the resource corresponding to this entity.",
      "$ref": "../type/basic.json#/definitions/href"
    },
    "changeDescription": {
      "description": "Change that lead to this version of the entity.",
      "$ref": "../type/entityHistory.json#/definitions/changeDescription"
    },
    "incrementalChangeDescription": {
      "description": "Change that lead to this version of the entity.",
      "$ref": "../type/entityHistory.json#/definitions/changeDescription"
    },
    "deleted": {
      "description": "When `true` indicates the entity has been soft deleted.",
      "type": "boolean",
      "default": false
    },
    "supportsRowLevelPassedFailed": {
      "description": "When `true` indicates the test case supports row level passed/failed.",
      "type": "boolean",
      "default": false
    },
    "domains" : {
      "description": "Domains the asset belongs to. When not set, the asset inherits the domain from the parent it belongs to.",
      "$ref": "../type/entityReferenceList.json"
    },
    "supportsDynamicAssertion": {
      "description": "When `true` indicates the test case supports dynamic assertions.",
      "type": "boolean",
      "default": false
    },
    "enabled": {
      "description": "When `true` indicates the test definition is available for creating test cases. System test definitions can only be disabled by users with appropriate permissions.",
      "type": "boolean",
      "default": true
     },
    "supportedServices": {
      "description": "List of services that this test definition supports. When empty, it implies all services are supported.",
      "type": "array",
      "items": {
        "type": "string"
      },
      "default": []
     },
    "sqlExpression": {
      "description": "SQL expression template for custom SQL-based test definitions. Supports substitution variables: {table} and {column} for runtime entity references, and {{paramName}} for user-defined parameters. This field is only applicable for test definitions with testPlatforms set to 'UMetadata' and is used to execute custom SQL queries for data quality validation.",
      "$ref": "../type/basic.json#/definitions/sqlQuery"
    },
    "validatorClass": {
      "description": "Class name of the validator to use for this test definition. This field is used to map the test definition to its corresponding validation logic in the data quality framework.",
      "type": "string"
    }
  },
  "required": ["name", "testPlatforms"],
  "additionalProperties": false
}

=== netboy001/OpenMetadata/umetadata-service/src/main/resources/json/data/tests/columnValueMinToBeBetween.json
{
    "name": "columnValueMinToBeBetween",
    "fullyQualifiedName": "columnValueMinToBeBetween",
    "displayName": "Column Value Min. To Be Between",
    "description": "This schema defines the test ColumnValueMinToBeBetween. Test the minimum value in a col is within a range.",
    "entityType": "COLUMN",
    "testPlatforms": ["UMetadata"],
    "supportedDataTypes": ["NUMBER", "INT", "FLOAT", "DOUBLE", "DECIMAL", "TINYINT", "SMALLINT", "BIGINT", "BYTEINT"],
    "parameterDefinition": [
      {
        "name": "minValueForMinInCol",
        "displayName": "Min",
        "description": "Expected minimum value in the column to be greater or equal than",
        "dataType": "INT",
        "validationRule": {
          "parameterField": "maxValueForMinInCol",
          "rule": "LESS_THAN_OR_EQUALS"
        }
      },
      {
        "name": "maxValueForMinInCol",
        "displayName": "Max",
        "description": "Expect minimum value in the column to be lower or equal than",
        "dataType": "INT",
        "validationRule": {
          "parameterField": "minValueForMeanInCol",
          "rule": "GREATER_THAN_OR_EQUALS"
        }
      }
    ],
    "supportsDynamicAssertion": true,
    "provider": "system",
  "enabled": true,
    "dataQualityDimension": "Accuracy",
    "validatorClass": "ColumnValueMinToBeBetweenValidator"
  }

=== netboy001/OpenMetadata/umetadata-service/src/main/resources/json/data/tests/tableColumnCountToEqual.json
{
  "name": "tableColumnCountToEqual",
  "fullyQualifiedName": "tableColumnCountToEqual",
  "displayName": "Table Column Count To Equal",
  "description": "This test defines the test TableColumnCountToEqual. Test the number of columns equal to a value.",
  "entityType": "TABLE",
  "testPlatforms": ["UMetadata"],
  "parameterDefinition": [
    {
      "name": "columnCount",
      "displayName": "Count",
      "description": "Expected number of columns to equal to a {value}",
      "dataType": "INT",
      "required": true
    }
  ],
  "provider": "system",
  "enabled": true,
  "dataQualityDimension": "Integrity",
  "validatorClass": "TableColumnCountToEqualValidator"
}

=== netboy001/OpenMetadata/umetadata-service/src/main/resources/json/data/tests/columnValuesSumToBeBetween.json
{
    "name": "columnValuesSumToBeBetween",
    "fullyQualifiedName": "columnValuesSumToBeBetween",
    "displayName": "Column Values Sum To Be Between",
    "description": "This schema defines the test ColumnValuesSumToBeBetween. Test the sum of the values of a col is within a range.",
    "entityType": "COLUMN",
    "testPlatforms": ["UMetadata"],
    "supportedDataTypes": ["NUMBER", "INT", "FLOAT", "DOUBLE", "DECIMAL", "TINYINT", "SMALLINT", "BIGINT", "BYTEINT"],
    "parameterDefinition": [
      {
        "name": "minValueForColSum",
        "displayName": "Min",
        "description": "Expected sum of values in the column to be greater or equal than",
        "dataType": "INT",
        "validationRule": {
          "parameterField": "maxValueForColSum",
          "rule": "LESS_THAN_OR_EQUALS"
        }
      },
      {
        "name": "maxValueForColSum",
        "displayName": "Max",
        "description": "Expected sum values in the column to be lower or equal than",
        "dataType": "INT",
        "validationRule": {
          "parameterField": "minValueForColSum",
          "rule": "GREATER_THAN_OR_EQUALS"
        }
      }
    ],
    "supportsDynamicAssertion": true,
    "provider": "system",
  "enabled": true,
    "dataQualityDimension": "Accuracy",
    "validatorClass": "ColumnValuesSumToBeBetweenValidator"
  }

=== netboy001/OpenMetadata/umetadata-service/src/main/resources/json/data/tests/columnValuesToNotMatchRegex.json
{
  "name": "columnValuesToNotMatchRegex",
  "fullyQualifiedName": "columnValuesToNotMatchRegex",
  "displayName": "Column Values To Not Match Regex",
  "description": "This schema defines the test ColumnValuesToNotMatchRegex. Test the values in a column to not match a given regular expression. ",
  "entityType": "COLUMN",
  "testPlatforms": ["UMetadata"],
  "supportedDataTypes": ["BYTES", "STRING", "MEDIUMTEXT", "TEXT", "CHAR", "VARCHAR", "LOWCARDINALITY"],
  "parameterDefinition": [
    {
      "name": "forbiddenRegex",
      "displayName": "RegEx Pattern",
      "description": "The regular expression the column entries should not match. For database without regex support (i.e. MSSQL, AzureSQL) this test will use `NOT LIKE`.",
      "dataType": "STRING",
      "required": true
    }
  ],
  "supportsRowLevelPassedFailed": true,
  "provider": "system",
  "enabled": true,
  "dataQualityDimension": "Validity",
  "validatorClass": "ColumnValuesToNotMatchRegexValidator"
}

=== netboy001/OpenMetadata/umetadata-service/src/main/resources/json/data/tests/columnValuesToBeNotNull.json
{
  "name": "columnValuesToBeNotNull",
  "fullyQualifiedName": "columnValuesToBeNotNull",
  "displayName": "Column Values To Be Not Null",
  "description": "This schema defines the test ColumnValuesToBeNotNull. Test the number of values in a column are null. Values must be explicitly null. Empty strings don't count as null. ",
  "entityType": "COLUMN",
  "testPlatforms": ["UMetadata"],
  "supportedDataTypes": ["NUMBER","TINYINT","SMALLINT","INT","BIGINT","BYTEINT","BYTES","FLOAT","DOUBLE","DECIMAL","NUMERIC","TIMESTAMP","TIMESTAMPZ","TIME","DATE","DATETIME","INTERVAL","STRING","MEDIUMTEXT","TEXT","CHAR","VARCHAR","BOOLEAN","BINARY","VARBINARY","ARRAY","BLOB","LONGBLOB","MEDIUMBLOB","MAP","STRUCT","UNION","SET","GEOGRAPHY","ENUM","JSON","UUID","VARIANT","GEOMETRY","POINT","POLYGON","LOWCARDINALITY"],
  "supportsRowLevelPassedFailed": true,
  "provider": "system",
  "enabled": true,
  "dataQualityDimension": "Completeness",
  "validatorClass": "ColumnValuesToBeNotNullValidator"
}

=== netboy001/OpenMetadata/umetadata-service/src/main/resources/json/data/tests/columnValuesToBeNotInSet.json
{
  "name": "columnValuesToBeNotInSet",
  "fullyQualifiedName": "columnValuesToBeNotInSet",
  "displayName": "Column Values To Be Not In Set",
  "description": "This schema defines the test ColumnValuesToBeNotInSet. Test the column values to not be in the set. ",
  "entityType": "COLUMN",
  "testPlatforms": ["UMetadata"],
  "supportedDataTypes": ["NUMBER", "INT", "FLOAT", "DOUBLE", "DECIMAL", "TINYINT", "SMALLINT", "BIGINT", "BYTEINT", "BYTES", "STRING", "MEDIUMTEXT", "TEXT", "CHAR", "VARCHAR", "BOOLEAN", "LOWCARDINALITY"],
  "parameterDefinition": [
    {
      "name": "forbiddenValues",
      "displayName": "Forbidden Values",
      "description": "An Array of values.",
      "dataType": "ARRAY",
      "required": true
    }
  ],
  "supportsRowLevelPassedFailed": true,
  "provider": "system",
  "enabled": true,
  "dataQualityDimension": "Validity",
  "validatorClass": "ColumnValuesToBeNotInSetValidator"
}

=== netboy001/OpenMetadata/umetadata-service/src/main/resources/json/data/tests/tableRowCountToBeBetween.json
{
  "name": "tableRowCountToBeBetween",
  "fullyQualifiedName": "tableRowCountToBeBetween",
  "displayName": "Table Row Count To Be Between",
  "description": "This defines the test TableRowCountToBeBetween. Test the number of rows to between to two values.",
  "entityType": "TABLE",
  "testPlatforms": ["UMetadata"],
  "parameterDefinition": [
    {
      "name": "minValue",
      "displayName": "Min",
      "description": "Expected number of columns should be greater than or equal to {minValue}. If minValue is not included, maxValue is treated as upperBound and there will be no minimum",
      "dataType": "INT",
      "validationRule": {
        "parameterField": "maxValue",
        "rule": "LESS_THAN_OR_EQUALS"
      }
    },
    {
      "name": "maxValue",
      "displayName": "Max",
      "description": "Expected number of columns should be less than or equal to {maxValue}. If maxValue is not included, minValue is treated as lowerBound and there will be no maximum",
      "dataType": "INT",
      "validationRule": {
          "parameterField": "minValue",
          "rule": "GREATER_THAN_OR_EQUALS"
      }
    }
  ],
  "supportsDynamicAssertion": true,
  "provider": "system",
  "enabled": true,
  "dataQualityDimension": "Integrity",
  "validatorClass": "TableRowCountToBeBetweenValidator"
}

=== netboy001/OpenMetadata/umetadata-service/src/main/resources/json/data/tests/tableRowCountToEqual.json
{
  "name": "tableRowCountToEqual",
  "fullyQualifiedName": "tableRowCountToEqual",
  "displayName": "Table Row Count To Equal",
  "description": "This schema defines the test TableRowCountToEqual. Test the number of rows equal to a value.",
  "entityType": "TABLE",
  "testPlatforms": ["UMetadata"],
  "parameterDefinition": [
    {
      "name": "value",
      "displayName": "Count",
      "description": "Expected number of rows to be equal to {Count}",
      "dataType": "INT",
      "required": true
    }
  ],
  "provider": "system",
  "enabled": true,
  "dataQualityDimension": "Integrity",
  "validatorClass": "TableRowCountToEqualValidator"
}
