=== netboy001/OpenMetadata/umetadata-spec/src/main/resources/json/schema/entity/services/connections/testConnectionDefinition.json
{
  "$id": "https://wondersgroup.com/schema/entity/services/connections/testConnectionDefinition.json",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "TestConnectionDefinition",
  "description": "TestConnection is the definition that will encapsulate the steps required to test a connection to a specific service.",
  "type": "object",
  "javaType": "org.umetadata.schema.entity.services.connections.TestConnectionDefinition",
  "javaInterfaces": ["org.umetadata.schema.EntityInterface"],
  "definitions": {
    "testConnectionStep": {
      "description": "Function that tests one specific element of the service. E.g., listing schemas, lineage, or tags.",
      "type": "object",
      "javaType": "org.umetadata.schema.entity.services.connections.TestConnectionStep",
      "properties": {
        "name": {
          "description": "Name of the step being tested",
          "type": "string"
        },
        "description": {
          "description": "What is the goal of the step",
          "type": "string"
        },
        "errorMessage": {
          "description": "In case of error this message should be displayed on UI, We define this message manually on test connection definition",
          "type": "string"
        },
        "mandatory": {
          "description": "Is this step mandatory to be passed?",
          "type": "boolean",
          "default": true
        },
        "shortCircuit": {
          "description": "This field if set to true, indicates that the step is important enough to break the process in case of failure.",
          "type": "boolean",
          "default": false
        }
      },
      "additionalProperties": false,
      "required": ["name", "mandatory", "description"]
    }
  },
  "properties": {
    "id": {
      "description": "Unique identifier of this test case definition instance.",
      "$ref": "../../../type/basic.json#/definitions/uuid"
    },
    "name": {
      "description": "Name of the Test Connection Definition. It should be the `type` of the service being tested, e.g., Mysql, or Snowflake.",
      "$ref": "../../../type/basic.json#/definitions/entityName"
    },
    "displayName": {
      "description": "Display Name that identifies this test definition.",
      "type": "string"
    },
    "description": {
      "description": "Description of the test connection def.",
      "$ref": "../../../type/basic.json#/definitions/markdown"
    },
    "fullyQualifiedName": {
      "description": "FullyQualifiedName same as `name`.",
      "$ref": "../../../type/basic.json#/definitions/fullyQualifiedEntityName"
    },
    "steps": {
      "description": "Steps to test the connection. Order matters.",
      "type": "array",
      "items": {
        "$ref": "#/definitions/testConnectionStep"
      }
    },
    "owners": {
      "description": "Owner of this TestConnection definition.",
      "$ref": "../../../type/entityReferenceList.json",
      "default": null
    },
    "version": {
      "description": "Metadata version of the entity.",
      "$ref": "../../../type/entityHistory.json#/definitions/entityVersion"
    },
    "updatedAt": {
      "description": "Last update time corresponding to the new version of the entity in Unix epoch time milliseconds.",
      "$ref": "../../../type/basic.json#/definitions/timestamp"
    },
    "updatedBy": {
      "description": "User who made the update.",
      "type": "string"
    },
    "impersonatedBy": {
      "description": "Bot user that performed the action on behalf of the actual user.",
      "$ref": "../../../type/basic.json#/definitions/impersonatedBy"
    },
    "href": {
      "description": "Link to the resource corresponding to this entity.",
      "$ref": "../../../type/basic.json#/definitions/href"
    },
    "changeDescription": {
      "description": "Change that lead to this version of the entity.",
      "$ref": "../../../type/entityHistory.json#/definitions/changeDescription"
    },
    "incrementalChangeDescription": {
      "description": "Change that lead to this version of the entity.",
      "$ref": "../../../type/entityHistory.json#/definitions/changeDescription"
    },
    "deleted": {
      "description": "When `true` indicates the entity has been soft deleted.",
      "type": "boolean",
      "default": false
    },
    "domains" : {
      "description": "Domains the asset belongs to. When not set, the asset inherits the domain from the parent it belongs to.",
      "$ref": "../../../type/entityReferenceList.json"
    }
  },
  "additionalProperties": false,
  "required": ["name", "steps"]
}

=== netboy001/OpenMetadata/umetadata-service/src/main/resources/json/data/testConnections/database/dremio.json
{
  "name": "Dremio",
  "displayName": "Dremio Cloud Test Connection",
  "description": "This Test Connection validates the access against Dremio Cloud REST API and basic metadata extraction of namespaces, folders, and tables.",
  "steps": [
    {
      "name": "CheckAccess",
      "description": "Validate that we can properly reach Dremio Cloud API and authenticate with the given Personal Access Token (PAT).",
      "errorMessage": "Failed to connect to Dremio Cloud. Please validate that your Project ID and Personal Access Token (PAT) are correct, and that the region/API URL is properly configured.",
      "shortCircuit": true,
      "mandatory": true
    },
    {
      "name": "GetDatabases",
      "description": "List all the namespaces (sources/spaces) available in the Dremio Cloud project. Namespaces are mapped as databases in UMetadata.",
      "errorMessage": "Failed to fetch namespaces from Dremio Cloud. Please validate if the PAT has enough privileges to read catalog metadata.",
      "mandatory": true
    },
    {
      "name": "GetSchemas",
      "description": "List all the folders within a namespace. Folders are mapped as schemas in UMetadata.",
      "errorMessage": "Failed to fetch folders from Dremio Cloud. Please validate if the PAT has enough privileges to read folder metadata.",
      "mandatory": true
    },
    {
      "name": "GetTables",
      "description": "From a given folder, list the tables and views. If no folder is specified, we'll list from a random folder.",
      "errorMessage": "Failed to fetch tables/views from Dremio Cloud. Please validate if the PAT has enough privileges to read dataset metadata.",
      "mandatory": true
    },
    {
      "name": "GetQueries",
      "description": "Check if we can access the query history (sys.project.history.jobs) to get query logs. These queries are analyzed in the usage & lineage workflow.",
      "errorMessage": "Failed to fetch query history from Dremio Cloud. Please validate if the PAT has privileges to access sys.project.history.jobs for usage and lineage extraction.",
      "mandatory": false
    }
  ]
}

=== netboy001/OpenMetadata/umetadata-service/src/main/resources/json/data/testConnections/database/oracle.json
{
    "name": "Oracle",
    "displayName": "Oracle Test Connection",
    "description": "This Test Connection validates the access against the database and basic metadata extraction of schemas, tables, views, and query history.",
    "steps": [
      {
        "name": "CheckAccess",
        "description": "Validate that we can properly reach the database and authenticate with the given credentials.",
        "errorMessage": "Failed to connect to oracle, please validate if the user has relevant permissions, if not, please provide the necessary permissions. For more details, please refer https://docs.u-metadata.org/connectors/database/oracle.",
        "shortCircuit": true,
        "mandatory": true
      },
      {
        "name": "PackageAccess",
        "description": "Validate that we can access Oracle stored packages.",
        "errorMessage": "Failed to access Oracle stored packages. Please verify the user has the necessary permissions to access Oracle packages.",
        "mandatory": false
      },
      {
        "name": "GetSchemas",
        "description": "List all the schemas available to the user.",
        "errorMessage": "Failed to fetch schemas, please validate if the user has enough privilege to fetch schemas.",
        "mandatory": true
      },
      {
        "name": "GetTables",
        "description": "From a given schema, list the tables belonging to that schema. If no schema is specified, we'll list the tables of a random schema.",
        "errorMessage": "Failed to fetch tables, please validate if the user has enough privilege to fetch tables.",
        "mandatory": true
      },
      {
        "name": "GetViews",
        "description": "From a given schema, list the views belonging to that schema. If no schema is specified, we'll list the views of a random schema.",
        "errorMessage": "Failed to fetch views, please validate if the user has enough privilege to fetch views.",
        "mandatory": false
      },
      {
        "name": "GetMaterializedViews",
        "description": "Validate that we can access materialized view definitions from DBA_MVIEWS.",
        "errorMessage": "Failed to fetch materialized views from DBA_MVIEWS. Please ensure the user has SELECT privilege on DBA_MVIEWS. This is required for extracting materialized view metadata.",
        "mandatory": false
      },
      {
        "name": "GetQueryHistory",
        "description": "Validate access to query history from gv$sql for usage and lineage extraction.",
        "errorMessage": "Failed to access query history from gv$sql. Please ensure the user has SELECT privilege on gv$sql or v$sql. This is required for usage tracking and lineage extraction features.",
        "mandatory": false
      }
    ]
  }
